version: '3.8'

services:
  web-app:
    build:
      context: ./apps/web-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - py-app
    networks:
      - app-network
    restart: unless-stopped

  py-app:
    build:
      context: ./apps/py-app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - LOG_LEVEL=info
    volumes:
      # Optional: Mount for live development
      # - ./apps/py-app:/app
      - temp_audio:/tmp/audio
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  app-network:
    driver: bridge

volumes:
  temp_audio: